#ifndef COMMONFILEPROCESSOR_GLOBAL_H
#define COMMONFILEPROCESSOR_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(COMMONFILEPROCESSOR_LIBRARY)
#define COMMONFILEPROCESSOR_EXPORT Q_DECL_EXPORT
#else
#define COMMONFILEPROCESSOR_EXPORT Q_DECL_IMPORT
#endif

#endif // COMMONFILEPROCESSOR_GLOBAL_H
